allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': false
  '@tailwindcss/oxide': false
  core-js: false
  prisma: true
  sharp: false
ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - prisma
  - sharp
